# Exoplanet Archive Intelligence
---

#### Source link: https://www.kaggle.com/datasets/kanchana1990/nasa-exoplanet-archive-intelligence
#### Author: `Kanchana Karunarathna`
#### License: `CC0: Public Domain`

#### Dataset Overview
---
Every confirmed exoplanet ever discovered, in one clean, ML-ready file. This dataset was constructed by querying the NASA Exoplanet Archive Planetary Systems Composite Parameters table (pscomppars) via the TAP API, retrieving all 6,150 confirmed planets with a full suite of planetary, orbital, and stellar parameters. Discovery records span from 1992 to 2026, covering the complete history of exoplanet science - from the first pulsar planets to the latest TESS discoveries. Raw measurements were enriched with seven engineered features built on standard astrophysical classification systems - the Fulton gap radius classification for planet types, the Harvard spectral sequence for star types, and equilibrium temperature thresholds from the habitable zone literature for HZ candidate flagging. Every record is traceable to a peer-reviewed publication in the NASA Exoplanet Archive. No synthetic rows. No estimated values. Nulls represent unmeasured parameters, not missing data - a standard and expected characteristic of observational astronomy datasets.

### Dataset Feature Descriptions
---

| Column | Description |
|--------|------------|
| planet_name | IAU-designated planet name |
| host_star | Host star identifier |
| n_stars | Number of stars in the system |
| n_planets | Number of confirmed planets in the system |
| discovery_method | Detection method (Transit, Radial Velocity, Microlensing, Imaging, etc.) |
| disc_year | Year of confirmed discovery |
| disc_facility | Discovery facility or telescope (Kepler, TESS, Hubble, etc.) |
| orbital_period_days | Planet orbital period in days |
| planet_radius_earth | Planet radius relative to Earth |
| planet_mass_earth | Planet mass relative to Earth |
| equilibrium_temp_k | Estimated equilibrium temperature in Kelvin |
| orbital_eccentricity | Orbital eccentricity (0 = circular orbit) |
| semi_major_axis_au | Orbital semi-major axis in astronomical units (AU) |
| star_temp_k | Host star effective temperature in Kelvin |
| star_radius_sun | Host star radius relative to the Sun |
| star_mass_sun | Host star mass relative to the Sun |
| star_age_gyr | Host star age in gigayears (billions of years) |
| star_surface_gravity | Logarithm of surface gravity (log g) |
| star_metallicity | Host star metallicity [Fe/H] |
| dist_from_earth_pc | Distance from Earth in parsecs |
| star_vmag | Host star apparent magnitude (V-band) |
| ra | Right ascension (decimal degrees) |
| dec | Declination (decimal degrees) |
| controversial_flag | Indicates if the planet is flagged as controversial |
| planet_type | Fulton gap classification (Sub-Earth to Super-Jupiter) |
| habitable_zone_flag | True if equilibrium temperature is between 200K–400K |
| multi_planet_system | True if host star has multiple confirmed planets |
| is_recent_discovery | True if discovered in 2020 or later |
| dist_category | Distance category (Nearby / Mid / Far / Distant) |
| star_type | Harvard spectral class (M-type to O-type) |
| orbital_period_cat | Orbital period category (Ultra-Short to Very-Long) |

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
data = pd.read_csv('../data/nasa_exoplanet_intelligence.csv')
data

,planet_name,host_star,n_stars,n_planets,discovery_method,disc_year,disc_facility,orbital_period_days,planet_radius_earth,planet_mass_earth,...,ra,dec,controversial_flag,planet_type,habitable_zone_flag,multi_planet_system,is_recent_discovery,dist_category,star_type,orbital_period_cat
0,Kepler-1167 b,Kepler-1167,1,1,Transit,2016.0,Kepler,1.003934,1.710000,3.570000,...,298.302660,47.693965,0,Super-Earth,False,False,False,Far(500-2kpc),K-type,Short(1-10d)
1,Kepler-1740 b,Kepler-1740,1,1,Transit,2021.0,Kepler,8.172400,3.323214,11.000000,...,293.873663,38.922455,0,Mini-Neptune,False,False,True,Far(500-2kpc),G-type(Sun-like),Short(1-10d)
2,Kepler-1581 b,Kepler-1581,1,1,Transit,2016.0,Kepler,6.283855,0.800000,0.437000,...,287.371320,39.603623,0,Sub-Earth,False,False,False,Mid(100-500pc),F-type,Short(1-10d)
3,Kepler-644 b,Kepler-644,1,1,Transit,2016.0,Kepler,3.173917,3.150000,10.100000,...,295.475702,43.493112,0,Mini-Neptune,False,False,False,Far(500-2kpc),F-type,Short(1-10d)
4,Kepler-1752 b,Kepler-1752,1,1,Transit,2021.0,Kepler,56.358501,4.540605,18.700000,...,290.854140,51.222743,0,Neptune-like,False,False,True,Far(500-2kpc),G-type(Sun-like),Medium(10-100d)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6145,KMT-2024-BLG-1870L b,KMT-2024-BLG-1870L,1,1,Microlensing,2026.0,KMTNet,NaN,13.800000,336.898111,...,272.465333,-26.882889,0,Gas Giant,False,False,True,Distant(2k+pc),Unknown,Unknown
6146,TOI-2267 b,TOI-2267 A,2,3,Transit,2025.0,Transiting Exoplanet Survey Satellite (TESS),2.289090,1.000000,0.972000,...,65.061496,84.900824,0,Super-Earth,False,True,True,Nearby(<100pc),M-type(Red Dwarf),Short(1-10d)
6147,TOI-813 b,TOI-813,1,1,Transit,2020.0,Transiting Exoplanet Survey Satellite (TESS),83.891100,6.710000,36.400000,...,72.694010,-60.905461,0,Gas Giant,False,False,True,Mid(100-500pc),G-type(Sun-like),Medium(10-100d)
6148,LHS 1903 b,LHS 1903,1,4,Transit,2026.0,Transiting Exoplanet Survey Satellite (TESS),2.155510,1.382000,3.280000,...,107.865826,48.327933,0,Super-Earth,False,True,True,Nearby(<100pc),M-type(Red Dwarf),Short(1-10d)
6149,TOI-375 d,TOI-375,1,3,Radial Velocity,2026.0,Multiple Observatories,297.900000,13.600000,445.595427,...,47.149903,-77.383327,0,Gas Giant,False,True,True,Mid(100-500pc),G-type(Sun-like),Long(100-365d)

In [4]:
# Checking dataset shape - rows and features number
data.shape

(6150, 31)

In [5]:
# Checking dataset names of the features
data.columns

Index(['planet_name', 'host_star', 'n_stars', 'n_planets', 'discovery_method',
       'disc_year', 'disc_facility', 'orbital_period_days',
       'planet_radius_earth', 'planet_mass_earth', 'equilibrium_temp_k',
       'orbital_eccentricity', 'semi_major_axis_au', 'star_temp_k',
       'star_radius_sun', 'star_mass_sun', 'star_age_gyr',
       'star_surface_gravity', 'star_metallicity', 'dist_from_earth_pc',
       'star_vmag', 'ra', 'dec', 'controversial_flag', 'planet_type',
       'habitable_zone_flag', 'multi_planet_system', 'is_recent_discovery',
       'dist_category', 'star_type', 'orbital_period_cat'],
      dtype='str')

In [6]:
# Checking dataset data types
data.dtypes

planet_name                 str
host_star                   str
n_stars                   int64
n_planets                 int64
discovery_method            str
disc_year               float64
disc_facility               str
orbital_period_days     float64
planet_radius_earth     float64
planet_mass_earth       float64
equilibrium_temp_k      float64
orbital_eccentricity    float64
semi_major_axis_au      float64
star_temp_k             float64
star_radius_sun         float64
star_mass_sun           float64
star_age_gyr            float64
star_surface_gravity    float64
star_metallicity        float64
dist_from_earth_pc      float64
star_vmag               float64
ra                      float64
dec                     float64
controversial_flag        int64
planet_type                 str
habitable_zone_flag        bool
multi_planet_system        bool
is_recent_discovery        bool
dist_category               str
star_type                   str
orbital_period_cat          str
dtype: object

In [32]:
for x in data.columns:
    missing = data[x].isna().sum()
    if missing > 0:
        print(f"{x}: {missing} missing values")

disc_year: 1 missing values
orbital_period_days: 334 missing values
planet_radius_earth: 50 missing values
planet_mass_earth: 31 missing values
equilibrium_temp_k: 1563 missing values
orbital_eccentricity: 938 missing values
semi_major_axis_au: 316 missing values
star_temp_k: 290 missing values
star_radius_sun: 314 missing values
star_mass_sun: 8 missing values
star_age_gyr: 1311 missing values
star_surface_gravity: 318 missing values
star_metallicity: 550 missing values
dist_from_earth_pc: 27 missing values
star_vmag: 295 missing values

In [33]:
data[data.disc_year.isna()]

,planet_name,host_star,n_stars,n_planets,discovery_method,disc_year,disc_facility,orbital_period_days,planet_radius_earth,planet_mass_earth,...,ra,dec,controversial_flag,planet_type,habitable_zone_flag,multi_planet_system,is_recent_discovery,dist_category,star_type,orbital_period_cat
5013,TOI-5789 c,TOI-5789,1,4,Transit,NaN,Transiting Exoplanet Survey Satellite (TESS),12.927748,2.86,5.0,...,302.773447,16.189714,0,Mini-Neptune,False,True,False,Nearby(<100pc),K-type,Medium(10-100d)