# Exoplanet Filtering for Earth-like Candidates
---
The goal of this notebook is to filter exoplanets based on criteria that approximate Earth-like conditions

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as st

In [3]:
# Load the dataset
data = pd.read_csv('../data/nasa_exoplanet_intelligence.csv')
data

,planet_name,host_star,n_stars,n_planets,discovery_method,disc_year,disc_facility,orbital_period_days,planet_radius_earth,planet_mass_earth,...,ra,dec,controversial_flag,planet_type,habitable_zone_flag,multi_planet_system,is_recent_discovery,dist_category,star_type,orbital_period_cat
0,Kepler-1167 b,Kepler-1167,1,1,Transit,2016.0,Kepler,1.003934,1.710000,3.570000,...,298.302660,47.693965,0,Super-Earth,False,False,False,Far(500-2kpc),K-type,Short(1-10d)
1,Kepler-1740 b,Kepler-1740,1,1,Transit,2021.0,Kepler,8.172400,3.323214,11.000000,...,293.873663,38.922455,0,Mini-Neptune,False,False,True,Far(500-2kpc),G-type(Sun-like),Short(1-10d)
2,Kepler-1581 b,Kepler-1581,1,1,Transit,2016.0,Kepler,6.283855,0.800000,0.437000,...,287.371320,39.603623,0,Sub-Earth,False,False,False,Mid(100-500pc),F-type,Short(1-10d)
3,Kepler-644 b,Kepler-644,1,1,Transit,2016.0,Kepler,3.173917,3.150000,10.100000,...,295.475702,43.493112,0,Mini-Neptune,False,False,False,Far(500-2kpc),F-type,Short(1-10d)
4,Kepler-1752 b,Kepler-1752,1,1,Transit,2021.0,Kepler,56.358501,4.540605,18.700000,...,290.854140,51.222743,0,Neptune-like,False,False,True,Far(500-2kpc),G-type(Sun-like),Medium(10-100d)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6145,KMT-2024-BLG-1870L b,KMT-2024-BLG-1870L,1,1,Microlensing,2026.0,KMTNet,NaN,13.800000,336.898111,...,272.465333,-26.882889,0,Gas Giant,False,False,True,Distant(2k+pc),Unknown,Unknown
6146,TOI-2267 b,TOI-2267 A,2,3,Transit,2025.0,Transiting Exoplanet Survey Satellite (TESS),2.289090,1.000000,0.972000,...,65.061496,84.900824,0,Super-Earth,False,True,True,Nearby(<100pc),M-type(Red Dwarf),Short(1-10d)
6147,TOI-813 b,TOI-813,1,1,Transit,2020.0,Transiting Exoplanet Survey Satellite (TESS),83.891100,6.710000,36.400000,...,72.694010,-60.905461,0,Gas Giant,False,False,True,Mid(100-500pc),G-type(Sun-like),Medium(10-100d)
6148,LHS 1903 b,LHS 1903,1,4,Transit,2026.0,Transiting Exoplanet Survey Satellite (TESS),2.155510,1.382000,3.280000,...,107.865826,48.327933,0,Super-Earth,False,True,True,Nearby(<100pc),M-type(Red Dwarf),Short(1-10d)
6149,TOI-375 d,TOI-375,1,3,Radial Velocity,2026.0,Multiple Observatories,297.900000,13.600000,445.595427,...,47.149903,-77.383327,0,Gas Giant,False,True,True,Mid(100-500pc),G-type(Sun-like),Long(100-365d)

In [4]:
in_habitat_zone = data[data['habitable_zone_flag'] == True]
in_habitat_zone

,planet_name,host_star,n_stars,n_planets,discovery_method,disc_year,disc_facility,orbital_period_days,planet_radius_earth,planet_mass_earth,...,ra,dec,controversial_flag,planet_type,habitable_zone_flag,multi_planet_system,is_recent_discovery,dist_category,star_type,orbital_period_cat
7,Kepler-263 c,Kepler-263,1,2,Transit,2014.0,Kepler,47.332773,2.470,6.66,...,292.469802,37.567794,0,Mini-Neptune,True,True,False,Far(500-2kpc),G-type(Sun-like),Medium(10-100d)
8,Kepler-1101 b,Kepler-1101,1,1,Transit,2016.0,Kepler,81.315106,2.470,6.66,...,294.569354,45.671162,0,Mini-Neptune,True,False,False,Far(500-2kpc),G-type(Sun-like),Medium(10-100d)
11,Kepler-560 b,Kepler-560,2,1,Transit,2016.0,Kepler,18.477644,1.720,3.61,...,300.206644,45.018240,0,Super-Earth,True,False,False,Mid(100-500pc),M-type(Red Dwarf),Medium(10-100d)
23,Kepler-1549 b,Kepler-1549,1,1,Transit,2016.0,Kepler,214.886545,2.570,7.13,...,286.052440,39.096028,0,Mini-Neptune,True,False,False,Far(500-2kpc),G-type(Sun-like),Long(100-365d)
33,Kepler-152 c,Kepler-152,1,2,Transit,2014.0,Kepler,88.255055,2.390,6.30,...,286.865383,41.988957,0,Mini-Neptune,True,True,False,Mid(100-500pc),K-type,Medium(10-100d)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6112,KOI-351 g,KOI-351,1,8,Transit,2013.0,Kepler,210.735140,7.718,15.00,...,284.433464,49.305124,0,Gas Giant,True,True,False,Far(500-2kpc),F-type,Long(100-365d)
6120,WASP-47 c,WASP-47,1,4,Radial Velocity,2015.0,La Silla Observatory,589.570000,NaN,447.00,...,331.203092,-12.019067,0,Unknown,True,True,False,Mid(100-500pc),G-type(Sun-like),Very-Long(365d+)
6125,GJ 411 b,GJ 411,1,2,Radial Velocity,2019.0,Haute-Provence Observatory,12.939400,1.450,2.69,...,165.834471,35.972317,0,Super-Earth,True,True,False,Nearby(<100pc),K-type,Medium(10-100d)
6129,HD 192310 b,HD 192310,1,2,Radial Velocity,2011.0,La Silla Observatory,74.720000,4.270,16.90,...,303.828471,-27.033756,0,Neptune-like,True,True,False,Nearby(<100pc),K-type,Medium(10-100d)
6131,TOI-4336 A b,TOI-4336 A,3,2,Transit,2024.0,Transiting Exoplanet Survey Satellite (TESS),16.336351,2.137,3.33,...,206.107013,-40.337350,0,Mini-Neptune,True,True,True,Nearby(<100pc),M-type(Red Dwarf),Medium(10-100d)